@startuml Klassendiagramm

class Cardmanagement{
    -loggedIn: boolean
    +logIn() : void
    -logIn(pPassword: String) : void
    +logOut() : void
    +getLoggedIn() : boolean
    +getUser() : User



}


class Menu{
    -sc : Scanner(System.in)

    +createUser() : User
    +logIn() : String
    +logOut(pCardmanagement : Cardmanagement) : void
    +showInventory() : Inventory
    +showMoney() : pMoney
    +checkProfile() : void
    +showMenu() : Menu
    +showShop() : Shop
    -breakLine() : void


}


class Shop{
    -changeMoney: double

    
    +showCards(pCards: Cards) : void
    +buyCard() : void

}


class User{
    -username : String
    -password : String
    -userID : int


    +User(pName : String, pPassword : String, pUserID : int, pMoney : float)
    +setPassword(pPassword : String) : void
    +changePassword(pPassword : String) : void
    +setUserID(pUserID : int) : void
    +getUserID(): int

}


class Person{
    -name: String
    -age: int
    -money: double

    +User(pName : String, pAge : int)
    +setName(pName : String) : void
    +getName(): String
    +setAge(pAge: int) : void
    +getAge() : int
    +setMoney(pMoney : int) : void
    +getMoney() : int
}


class Cards{
    -rarity : String
    -name : String
    -cardID : int
    -price: float

    +showName(pName : String)
    +showRarity(pRarity : String)
    +showPrice(pPrice : int)
    +showCardID(pCardID : int)

}


class Inventory{
+card : Cards[20]
+showCards()
+sellCard() : void
+giveMoney()
+showCards()
+showCards(pCards: Cards) : void
+sellCard() : void
}


class Cardslist{
    +randomCard() : void
}

Cardmanagement *-- "1" Menu : hat ein Menu
User *-- "1" Inventory : hat ein Inventar
Cardmanagement *-- "4" User : hat 4 User
Menu *-- "1" Shop : hat einen Shop
Shop *-- "5" Cardslist : hat 5 Karten 
Inventory *-- "20" Cardslist : hat 20 Karten
Cardslist *-- "151" Cards : hat 151 Karten
Person <|-- User : User erbt von Person

@enduml