//Noch nicht fertig
@startuml


Menu -> Shop :showcards()
Shop --> User : Zeigt Karten  []


User -> Shop :buycard [1]
Shop --> Inventory: tranferiert die Karte

User -> Inventory : sellcard()
Inventory -> Shop : information Karte wird verkauft
Shop --> User : changeMoney()


Menu -> User: changepassword()
User --> Menu: eingabe neues Passwort




@enduml